env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - airbnb-base
  - airbnb-typescript/base
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules: {
  no-param-reassign: off,
  import/prefer-default-export: off,
  arrow-body-style: off,
  no-console: error
}
ignorePatterns:
  - /node_modules
  - /dist
  - /src/assets
